{{- if .Values.secrets.enabled }}
{{- range .Values.secrets.secrets -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
type: {{ .type }}
data: {{ toYaml .data | nindent 2 }}
---
{{- end }}
{{- end }}
