{{- if eq .Values.serviceAccount.enabled true }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  labels: {{ toYaml .Values.deployment.labels | nindent 4 }}

  {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- if hasKey .Values.serviceAccount "automountServiceAccount" }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccount }}
{{- end }}

{{- end }}
